### ISSUE TITLE
May I know how to get the MFCC features?

### ISSUE THREAD

**Issue by ilovecv** [catalina17/XFlow#1]
Hi,

May I know how you get the MFCC features? Like the parameters you used. Thank you very much!

**Comment by catalina17** [comment]
Hi,

Thanks for the question! I used the librosa [mfcc](https://github.com/librosa/librosa/blob/main/librosa/feature/spectral.py#L1740) method with `n_mfcc=26`. Note that you can also play around with the `kwargs`, which are parameters for [melspectrogram](https://github.com/librosa/librosa/blob/main/librosa/feature/spectral.py#L1873) - I don't remember which values I used (worked on extracting MFCCs more than 3 years ago!), but the parameters `hop_length` and `win_length` might need tweaking to align with the number of frames extracted from videos.

Hope this helps,
Catalina
